### ISSUE TITLE
Tabs comoponent bug

### ISSUE THREAD

**Issue by zubacm** [lanaco/lnc-react-ui#368]
Tabs component throws this error
![image](https://github.com/lanaco/lnc-react-ui/assets/46137823/e0fd85c9-5e19-4b56-9a1f-1fc236a5dc36)

Code:
![image](https://github.com/lanaco/lnc-react-ui/assets/46137823/d6e16ba8-5e63-4f12-b7ff-84c6faa89b51)

onClick event on TabItem is probably causing problem, find out why.

**Comment by brckalo** [comment]
From this [question](https://stackoverflow.com/questions/53945281/warning-unknown-event-handler-property-onheaderclick-it-will-be-ignored), we can conclude that the problem is in the name of the _onItemClick_ function. We should try changing it to another name, e.g., handleItemClick. This function appears in the following files: TabItem.js and index.js (Tabs).

Also, this function is missing in PropTypes objects (data type and default value).
